/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-fixed': '#e9ddff',
        'on-secondary-container': '#00515d',
        'surface-container-low': '#181b25',
        'secondary': '#5de6ff',
        'tertiary-container': '#b175ec',
        'surface-container': '#1c1f29',
        'background': '#0f131c',
        'outline': '#958ea0',
        'on-surface-variant': '#cbc3d7',
        'on-primary-fixed': '#23005c',
        'inverse-on-surface': '#2c303a',
        'on-surface': '#dfe2ef',
        'secondary-fixed': '#a2eeff',
        'error': '#ffb4ab',
        'primary': '#d0bcff',
        'secondary-fixed-dim': '#2fd9f4',
        'surface-dim': '#0f131c',
        'on-error-container': '#ffdad6',
        'tertiary': '#ddb8ff',
        'on-primary': '#3c0091',
        'surface': '#0f131c',
        'inverse-primary': '#6d3bd7',
        'surface-container-highest': '#31353f',
        'surface-container-lowest': '#0a0e17',
        'error-container': '#93000a',
        'secondary-container': '#00cbe6',
        'on-secondary-fixed': '#001f25',
        'on-tertiary-fixed': '#2c0051',
        'on-tertiary-container': '#400071',
        'on-secondary-fixed-variant': '#004e5a',
        'tertiary-fixed-dim': '#ddb8ff',
        'primary-fixed-dim': '#d0bcff',
        'on-primary-container': '#340080',
        'primary-container': '#a078ff',
        'on-primary-fixed-variant': '#5516be',
        'on-error': '#690005',
        'on-background': '#dfe2ef',
        'on-secondary': '#00363e',
        'tertiary-fixed': '#f0dbff',
        'surface-variant': '#31353f',
        'surface-container-high': '#262a34',
        'outline-variant': '#494454',
        'on-tertiary': '#490081',
        'on-tertiary-fixed-variant': '#62259b',
        'surface-bright': '#353943',
        'surface-tint': '#d0bcff',
        'inverse-surface': '#dfe2ef',
        'accent': '#8B5CF6'
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
      backdropBlur: {
        xs: '2px',
      }
    },
  },
  plugins: [],
}
